{% set name = "timerit" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/timerit-{{ version }}.tar.gz
  sha256: a12a7db82d8cc6a0e1bc3258e6eead7a21c617da5605083118d5c3e99927fb69

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=41.0.1
    - pip
  run:
    - python >=3.6

test:
  imports:
    - timerit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Erotemic/timerit
  summary: A powerful multiline alternative to timeit
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
