schema_version: 1

context:
  name: timerit
  version: "1.2.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/timerit-${{ version }}.tar.gz
  sha256: 735194b3ac1e06764d65344d2325fb5fc6b3e9a737ae157a6012f453c2bd394a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=41.0.1
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - timerit
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: A powerful multiline alternative to timeit
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/Erotemic/timerit

extra:
  recipe-maintainers:
    - jan-janssen
